name: real_san_jose
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Ãconos y utilidades
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  flutter_rating_bar: ^4.0.1
  carousel_slider_plus: ^7.1.0
  persistent_bottom_nav_bar: ^6.2.1
  dropdown_button2: ^2.3.9
  url_launcher: ^6.3.1
  pin_code_text_field: ^1.8.0
  fluttertoast: ^8.2.10
  flutter_svg: ^2.0.10+1
  awesome_circular_chart: ^1.1.0

  # ğŸ“… Calendarios
  calendar_timeline: ^1.1.3
  horizontal_week_calendar: ^0.0.18
  table_calendar: ^3.0.9   # ğŸ‘ˆ agregado para evitar error

  # ğŸ“Š GrÃ¡ficas
  fl_chart: ^0.69.0

  # ğŸ“¸ Multimedia
  image_picker: ^1.1.2

  # ğŸ’¾ Almacenamiento local
  shared_preferences: ^2.2.2

dependency_overrides:
  shared_preferences_android: ^2.2.2

dev_dependencies:
  flutter_launcher_icons: "^0.10.0"
  change_app_package_name:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/iconoPrincipal.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/iconoPrincipal.png"
  min_sdk_android: 24

flutter:
  uses-material-design: true

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/google_sans.ttf

  assets:
    - assets/icons/
    - assets/images/
